Simple_Django-Blog/djangoblog/src/djangoblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login_view, logout_view
urlpatterns = []

urlpatterns = [
    url(r'^admin/', admin.site.urls, name = 'admin'),
    url(r'^posts/', include("posts.urls", namespace = 'posts')),
    url(r'^logout/', logout_view, name = 'logout'),
    url(r'^$', login_view, name='login'),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Simple_Django-Blog/djangoblog/src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
	#/posts/
    url(r'^$', views.post_list, name = 'list'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name = 'detail'),
    
    #/posts/create
    url(r'^create/$', views.post_create, name = 'create'),
    
    #/posts/id/update
	url(r'^(?P<id>\d+)/edit-post/$', views.post_update, name = 'update'),
	url(r'^(?P<id>\d+)/delete-post/$', views.post_delete, name = 'delete'),

    #Ajax Calls
    url(r'^ajax/search/$', views.AjaxSearch),
]

Simple_Django-Blog/djangoblog/src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Simple_Django-Blog/djangoblog/src/posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default = 1)
	title = models.CharField(max_length=120)
	author = models.CharField(max_length=120)
	image = models.FileField(null = True, blank = True)
	content = models.TextField()
	update = models.DateTimeField(auto_now=True,auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)
	publish = models.DateField(auto_now = False, auto_now_add = False)
	comment = models.ForeignKey('Comment', null = True)

	def __unicode__(self):
		return self.title
		
	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("posts:detail", kwargs = {"id": self.id})
	
	class Meta:
		ordering = ["-timestamp", "-update"]
		
class Comment(models.Model):
	content = models.TextField(null = True)
	timestamp = models.DateTimeField(null = True)
	author = models.CharField(max_length=120, null = True)

	parent = models.ForeignKey('self', null=True, blank=True)

	def get_children(self):
		return Comment.objects.filter(parent=self)

	def __unicode__(self):
		return self.user.username

	def __str__(self):
		return self.user.username

Simple_Django-Blog/djangoblog/src/accounts/forms.py
from django import forms

Simple_Django-Blog/djangoblog/src/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta :
		model = Post
		fields = [
			"title", 
			"image",
			"content",
			"publish",
		]
		

Simple_Django-Blog/djangoblog/src/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import (
	authenticate,
	login,
	logout,
	)

def login_view(request):
	if 'registration' in request.POST:
		new_user ,created= User.objects.get_or_create(username = request.POST.get("new_email",False), email = request.POST.get("new_email", False))
		if created:
			new_user.set_password(request.POST.get("new_password", False))
			new_user.save()

	if 'login' in request.POST:
		post_username = request.POST.get("username", False)
		post_password = request.POST.get("password", False)

		user = authenticate(username = post_username, password = post_password)
		if user is not None:
			if user.is_active:
				login(request, user)

	if request.user.is_authenticated:
		return HttpResponseRedirect('/posts/')
	else:
		return render(request, "login_form.html", {})
	
def logout_view(request):
	if request.user.is_authenticated:
		logout(request)
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

Simple_Django-Blog/djangoblog/src/posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q
# Create your views here.

	
#POSTS LISTS
def post_list(request):
	query2 = request.POST.get("sort",False)
	print(query2)
	list_posts = Post.objects.all()
	user_posts = Post.objects.all()
	user_posts = user_posts.filter(
		Q(author__contains=request.user.username)
		).distinct()

	if 'search_submit' in request.POST:
		query = request.POST.get("search")
		list_posts = list_posts.filter(
		Q(title__icontains = query)|
		Q(content__icontains = query)|
		Q(author__contains = query)|
		Q(publish__icontains = query)
		).distinct()

	if query2 == "Author":
		list_posts = Post.objects.order_by('author')
	if query2 == "Date":
		list_posts = Post.objects.order_by('publish')

	paginator = Paginator(list_posts, 5)
	page_request_var = "page"
	page = request.GET.get(page_request_var)
		
	try:
		get_post = paginator.page(page)
	except PageNotAnInteger:
		get_post = paginator.page(1)
	except EmptyPage:
		get_post = paginator.page(paginator.num_pages)
	
	context = {
	"list_posts": get_post,
	"user_posts": user_posts,
	"title": "Django Blogs Gaming",
	"page_request_var": page_request_var,

	}
	return render(request, "post_list.html", context)

#POSTS DETAILS
def post_detail(request, id = None):
	obj_instance = get_object_or_404(Post, id = id)
	context = {
		"title": obj_instance.title,
		"object_instance": obj_instance,
	}
	return render(request, "post_detail.html", context)
	
#POSTS CREATE 
def post_create(request):
	
	if not request.user.is_authenticated():
		raise Http404
		
	createform = PostForm(request.POST or None, request.FILES or None)
	context = {
		"create_form": createform,
	}
	
	if createform.is_valid():
		obj_instance = createform.save(commit = False)
		obj_instance.author = request.user.username
		obj_instance.save()
		return HttpResponseRedirect('/posts/')
		
	return render(request, "post_form.html", context)

#POSTS UPDATE
def post_update(request, id = None):
	if not request.user.is_authenticated():
		raise Http404
		
	obj_instance = get_object_or_404(Post, id = id)
	createform = PostForm(request.POST or None,request.FILES or None, instance = obj_instance)

	if createform.is_valid():
		obj_instance = createform.save(commit = False)
		obj_instance.save()
		return HttpResponseRedirect(obj_instance.get_absolute_url())
	
	context = {
		"title": obj_instance.title,
		"object_instance": obj_instance,
		"create_form": createform,
	}
	return render(request, "post_form.html", context)

#POSTS DELETE
def post_delete(request, id = None):
	if not request.user.is_authenticated():
		raise Http404
		
	obj_instance = get_object_or_404(Post, id = id)
	obj_instance.delete()
	return redirect("posts:list")
	

#AJAX CALLS
def AjaxSearch(request):
	if request.method == 'POST':
		search  = request.POST.get("search",False);
	print("GAGO MAMAM MAOISJHASHUAIHSNUAHSUIHASIUHASIO")

Simple_Django-Blog/djangoblog/src/templates/base.html
<!--DOCTYPE html-->
{% load staticfiles %}
<html>
	<head>
	<title>{% block head_title %}Django Comet{% endblock head_title %}</title>
    <link rel="shortcut icon" href="../static/pictures/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../static/pictures/favicon.ico" type="image/x-icon">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link rel = 'stylesheet' href = '{% static "/css/base.css" %}'/>
    <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
	<style>

		{% block style %}
            @media (max-width: 600px) {
              .facet_sidebar {
                display: none;
              }
            }

            body {
                margin-top: 75px;
            }
		{% endblock style %}
	</style>
	</head>

	<body>
		<div id="fb-root"></div>

        <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
            <div class="container">

                <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                    <ul class="nav navbar-header">
                       <li><a href='{% url "posts:list" %}' class="navbar-brand"><img src='{% static "/pictures/comet_fb.png" %}' height = 37 width = 37></a></li>
                   </ul>

                    <ul class="nav navbar-nav navbar-left">
                        <form onsubmit="return False;" id="search_post" class = "navbar-form" role = "search">{% csrf_token %}
                            <input id="search" name="search" class="form-control" style = "width:500px; height:35px;" type = 'text' placeholder = 'Search posts' value = '{{ request.GET.query }}'/>
                            <button onclick="search_post" name="search_submit" type="submit" value = 'Search' style = "height:35px;" class="btn btn-success glyphicon glyphicon-search"></button>
                        </form>

                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_authenticated %}
                            <li><a class="navbar-brand pull-right"  style = "color: lawngreen;" href='{% url "login" %}'><span class="glyphicon glyphicon-log-in pull-right"></span> Login</a></li>
                        {% else %}
                            <li ><a class="navbar-brand pull-right" style = "color: lawngreen;" href='{% url "posts:list"  %}'><span class="glyphicon glyphicon-user"></span> {{request.user.username}} </a></li>
                            <li><a class="navbar-brand pull-right" style = "color: lawngreen;" href='{% url "logout" %}'><span class="glyphicon glyphicon-new-window "></span> Logout </a> </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </header>

        <!--
         <nav class="navbar navbar-default" style= "background-color:black;">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href='{% url "posts:list" %}'>PROJECT SPRINT BLOG</a>
            </div>
            <ul class="nav navbar-nav">
              <li class="active"><a href='{% url "posts:list" %}'>Home</a></li>

              <li><a href='{% url "posts:create" %}'>Create Post</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                  <li><a href='{% url "login" %}'><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% else %}

                    <li>  <a href='{% url "posts:list"  %}'><span class="glyphicon glyphicon-user"></span>{{user.username}}</a></li>
                    <li>  <a href='{% url "logout" %}'><span class="glyphicon glyphicon-new-window"></span>Logout</a></li>


				{% endif %}
            </ul>
          </div>
        </nav>
        -->
		{% block content %}

		{% endblock content %}

        <footer>
        <div class="container">

        </div>
        </footer>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
    <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '200',
          width: '235',
          videoId: 'wdDEtdHlKNo',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.playVideo();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 6000);
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
    <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
    <script>
        function search_post(){
            $('.ajaxProgress').show();
            $.ajax({
                type: "POST",
                url:"/ajax/search/"
                datatype: "json",
                async: true,
                data:{
                    csrfmiddlewaretoken:'{{csrf_token}}',
                },

                success:function(json){
                    $('.ajaxProgress').hide();
                }
            });
        }
    </script>
    <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=595ddbb7b4af5d001186f321&product=sticky-share-buttons"></script>
    </body>
</html>

Simple_Django-Blog/djangoblog/src/templates/login_form.html
<html>

	<title>Django Comet</title>
	<head>
		<link rel="stylesheet" href="../static/css/textillate-master/assets/animate.css">
		<link type="text/css" rel="stylesheet" href="style.css" />
		<link rel="shortcut icon" href="../static/pictures/favicon.ico" type="image/x-icon">
		<link rel="icon" href="../static/pictures/favicon.ico" type="image/x-icon">
		<link rel = 'stylesheet' href = "../static/css/login.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	</head>
	<body>
		<div class="fb-header-base"></div>

		<div class="fb-header">
			<div id="img1" class="fb-header"><a href = '/posts/'><img src="../static/pictures/comet.png" height = 70 width = 220 /></a></div>
			 	<form  method = 'POST' id = "login" action = ''>{% csrf_token %}
					<div id="form1" class="fb-header">Email Address<br>
					<input class ="form-control" placeholder="Email Address" type="username" name="username" required /><br>
					</div>
					<div id="form2" class="fb-header">Password<br>
					<input class ="form-control" placeholder="Password" type="password" name="password" required/><br>
					</div>
					<button type="submit" class="submit1" name = "login">Log in</button>
			 	</form>

		</div>
		<div class="fb-body">
			<img  class="fb-body" id="img3" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Moon_rotating_full_220px.gif"/>
			<div data-in-effect="wobble" class="fb-body intro_word"><!--data-in-effect="wobble"-->COMET helps you connect and share with awesome people </div>
			<div id="night-view"></div>
			<div id="intro2" class="fb-body">Create an account</div>
			<div id="img2" class="fb-body"><img height = 650  width= 1300 style = "opacity: 0.5; filter: alpha(opacity=30); " src="../static/pictures/world2.png" /></div>
			<div id="intro3" class="fb-body">It's free and always will be.</div>
			<div id="form3" class="fb-body">
				<form  method = 'POST' action = ''>{% csrf_token %}
					<input placeholder="First Name" type="text" id="namebox" name="new_first_name" required/>
					<input placeholder="Last Name" type="text" id="namebox" name="new_last_name" required/> <br>
					<input placeholder="Email Address" type="text" id="mailbox1" name="new_email" required/><br>
					<input placeholder="Re-enter email" type="text" id="mailbox2" name="valid_new_email" required/><br>
					<input placeholder="Password" type="password" id="password1" name="new_password" required/><br>
					<input placeholder="Re-enter password" type="password" id="password2" name="valid_new_password" required/><br><hr style="border-top: 3px solid darkslategrey;">
					<p id="intro4"><b>By clicking Create Account, you agree to our Terms and that you have read our Data Policy, including our Cookie Use. You may receive SMS Notifications from Comet and can opt out at any time.</b></p>
					<input type="submit" class="button2" value="Create an account" name = "registration"/>
					<br><hr style="border-top: 3px solid darkslategrey;">
					<p id="intro5">Create a Page for a celebrity, band or business.</p>
				</form>

			</div>

		</div>
		<div class="fb-body-footer"></div>

 	<script src="../static/js/input_validation.js"></script>
 	<script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src = "./static/css/textillate-master/jquery.textillate.js"></script>
    <script src = "./static/css/textillate-master/assets/jquery.lettering.js"></script>
    <script>
		$(function() {
			$('.intro_word').textillate();
		})
    </script>
	</body>

</html>

<!--
{% block content %}
<div class = 'col-sm-6 col-sm-offset-3'>
	<div  class="panel panel-default">
		<div class="panel-heading"><h1> DJANGO BLOG {{title}}</h1></div>

<hr/>
<form method = 'POST' action = '' enctype = 'multipart/form-data'>{% csrf_token %}

	{{form.as_p}}
	<input type = 'submit' class = 'btn btn-success' value = "Submit" />

</form>
	</div>
</div>
{% endblock content %}
-->

Simple_Django-Blog/djangoblog/src/templates/post_detail.html
{%extends "base.html" %}

{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}
{% load staticfiles %}
{% block content %}
<div class = "col-md-2 col-sm-2 col-xs-2"></div>
<div class = "col-md-6 col-sm-6 col-xs-6">
    <div class="panel panel-default">
        <div class ="panel-heading"><h1 style="font-family: Courier; font-size:40px;"> {{ title }}</h1></div>
        <div class ="panel-body">


            {% if object_instance.image %}
                <img src = '{{ object_instance.image.url }}' height = 1000 width = 500 align = "middle" class="img-responsive center-block" />
            {% else %}
                <img src="http://placehold.it/900x300" class="img-responsive center-block">
            {% endif %}
            <hr>
            <a href = ' {{ request.path }}edit-post/'> <input type = 'submit' value = 'Edit' /></a> <a href = '{{ request.path }}delete-post/''> <input type = 'submit' value = 'Delete' /></a>

            {% if user.is_active %}<h3> <p>Author: {{object_instance.author}}</p></h3> {% endif %}</br>
            <h4> Date Published: {{object_instance.publish}} </h4> </br>
            {{ object_instance.content|linebreaks }}</br>
        </div>
        <div class = "panel-footer">
            <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
            <div class="fb-comments" data-href="{{ request.build_absolute_url }}" data-numposts="5"></div>
        </div>

    </div>

</div>
<div class="col-md-2 col-sm-2 col-xs-2 " style = "background-color: #4d4d4d; ">
     </br>

     <div class="well text-center">
            <p class="lead">
                Don't want to miss updates? Please click the below button!
            </p>
         <a style = "font-family: 'Source Code Pro'; font-size: 18px; href="https://www.linkedin.com/in/john-edel-tamani-9a8478131/"><b>Subscribe to my feed</b></a>
     </div>
     <hr>
     <div style="width:100%;height:0;padding-bottom:115%;position:relative;"><iframe src="https://giphy.com/embed/jxxZgq4DA6E92" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/mark-zuckerberg-jxxZgq4DA6E92">via GIPHY</a></p>
     <hr>
     <div class="panel panel-default">
        <div class="panel-heading">
            <h4 style="font-family: 'Source Code Pro'; color:green; "><b>Popular Blog Sites</b></h4>
        </div>
        <ul class="list-group">
            <li style="font-family:Lato; font-size: 18px" class="list-group-item"><a href="https://wordpress.com/"><img src = '{% static "/pictures/wordpress.png" %}' width = 40 height = 40/>Wordpress.com</a></li>
            <li style="font-family:Lato; font-size: 18px" class="list-group-item"><a href="https://www.tumblr.com/"><img src = '{% static "/pictures/tumblr.png" %}' width = 40 height = 30/>Tumblr</a></li>
            <li style="font-family:Lato; font-size: 18px" class="list-group-item"><a href="https://www.weebly.com/"><img src = '{% static "/pictures/weebly.png" %}' width = 40 height = 30/>Weebly</a></li>
            <li style="font-family:Lato; font-size: 18px" class="list-group-item"><a href="https://www.blogger.com/about/?r=2"><img src = '{% static "/pictures/blogger.png" %}' width = 40 height = 30/>Blogger</a></li>
            <li style="font-family:Lato; font-size: 18px" class="list-group-item"><a href="https://www.wix.com/"><img src = '{% static "/pictures/wix.png" %}' width = 40 height = 30/>Wix</a></li>
        </ul>
    </div>
     <hr>
     <div style="width:100%;height:0;padding-bottom:80%;position:relative;"align="center"><iframe align="center" src="http://widget.calendarlabs.com/v1/quot.php?cid=101&uid=801236995&c=random&l=en&cbg=000000&cb=2&cbc=FFFFFF&cf=calibri&cfg=FFFFFF&qfs=bi&qta=right&tfg=FFFFFF&tfs=bi&afc=FFFFFF&afs=i" width="188" height="210" marginwidth=0 marginheight=0 frameborder=0 scrolling=no allowtransparency='true'>Loading...</iframe><div align="center" style="width:140px;font-size:10px;color:#333;">Daily Quotes by <a href="https://www.calendarlabs.com/" target="_blank" rel="nofollow" style="font-size:10px;text-decoration:none;color:#333;">CalendarLabs</a></div></div><!-------Do not change above this line------->
     <hr>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 style="font-family: 'Source Code Pro'; color:green;"><b>Recent Comments</b></h4>
        </div>
        <ul class="list-group">
            <li class="list-group-item"><a href="#">I don't believe in astrology but still your writing style is really great! - <em>john</em></a></li>
            <li class="list-group-item"><a href="#">Wow.. what you said is really true! I'm an aries though - <em>Anto</em></a></li>
            <li class="list-group-item"><a href="#">Does capricorn and aries is compatibile? - <em>Sarah</em></a></li>
            <li class="list-group-item"><a href="#">I'm a cancer woman been in love with Leo. Will this work? - <em>Mary</em></a></li>
        </ul>
    </div>
    <hr>

</div>
{% endblock content %}

Simple_Django-Blog/djangoblog/src/templates/post_form.html
{%extends "base.html" %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-3'>
<h1> Form</h1>
<form method = 'POST' action = '' enctype = 'multipart/form-data'>{% csrf_token %}
	{{create_form.as_p}}
	<input type = 'submit' class = 'btn btn default' value = 'Create Post' />
</form>
</div>
{% endblock content %}

Simple_Django-Blog/djangoblog/src/templates/sample.html
<!DOCTYPE HTML>
<html>
  <head>
    <script src="http://www.webglearth.com/v2/api.js"></script>
    <script>
      function initialize() {
        var options = {atmosphere: true, center: [0, 0], zoom: 0};
        var earth = new WE.map('earth_div', options);
        WE.tileLayer('http://tileserver.maptiler.com/nasa/{z}/{x}/{y}.jpg', {
          minZoom: 0,
          maxZoom: 5,
          attribution: 'NASA'
        }).addTo(earth);
      }
    </script>
    <style>
      html, body{padding: 0; margin: 0;}
      #earth_div{top: 0; right: 0; bottom: 0; left: 0;
                 background-color: #000; position: absolute !important;}
      </style>
      <title>WebGL Earth API: Satellite</title>
    </head>
    <body onload="initialize()">
      <div id="earth_div" width = 20px height = 20px></div>
  </body>
</html>